version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    environment:
      - NODE_ENV=dev
      - DB_HOST=db
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 9000:9000
