version: '3'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/volumes/postgres -c log_min_messages=DEBUG5 -c log_statement=all
    volumes:
      - ./volumes/postgres:/volumes/postgres
    ports:
      - "5433:5432"
    expose:
      - "5432"
    networks:
      - app
    environment:
      - PGDATA=/volumes/postgres
      - POSTGRES_USER=ratio_test
      - POSTGRES_PASSWORD=ratio_test
      - POSTGRES_DB=ratio_test

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=dev
      #- DB_HOST=db
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 9000:9000
    env_file:
      - .env
    networks:
      - app

networks:
  app:
    driver: bridge